format = """
$username\\
$hostname\\
$directory\\
$git_branch\\
$git_status\\
$cmd_duration\\
$line_break\\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$branch](bold purple) "

[git_status]
format = "[$all_status](bold red) "
